ALTER TABLE users
ALTER COLUMN userid ADD GENERATED ALWAYS AS IDENTITY
(START WITH 100000001);

ALTER TABLE events
ALTER COLUMN eventid ADD GENERATED ALWAYS AS IDENTITY
(START WITH 100000001);

ALTER TABLE payments
ALTER COLUMN paymentid ADD GENERATED ALWAYS AS IDENTITY
(START WITH 100000001);

ALTER TABLE refund
ALTER COLUMN refundid ADD GENERATED ALWAYS AS IDENTITY
(START WITH 100000001);

ALTER TABLE booking
ALTER COLUMN bookingid ADD GENERATED ALWAYS AS IDENTITY
(START WITH 100000001);